name: Verible lint push
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        config_file: '${GITHUB__WORKSPACE}/tools/lint/verible.config'
        extensions: |
          .sv
          .v
          .vh
          .svh
        github_token: ${{ secrets.GITHUB_TOKEN }}
