name: Verible formatter push
on:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: chipsalliance/verible-formatter-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
